 schemaname |      tablename       |                     policyname                     | permissive |  roles   |  cmd   |                                                                                                          qual                                                                                                          |                                                               with_check                                                                
------------+----------------------+----------------------------------------------------+------------+----------+--------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------
 public     | Account              | Users can insert own accounts                      | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | ("userId" = (auth.uid())::text)
 public     | Account              | Users can delete own accounts                      | PERMISSIVE | {public} | DELETE | ("userId" = (auth.uid())::text)                                                                                                                                                                                        | 
 public     | Session              | Users can view own sessions                        | PERMISSIVE | {public} | SELECT | ("userId" = (auth.uid())::text)                                                                                                                                                                                        | 
 public     | Account              | Users can view own accounts                        | PERMISSIVE | {public} | SELECT | ("userId" = (auth.uid())::text)                                                                                                                                                                                        | 
 public     | CrisisAlert          | System can create crisis alerts                    | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | true
 public     | Session              | Users can insert own sessions                      | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | ("userId" = (auth.uid())::text)
 public     | Session              | Users can delete own sessions                      | PERMISSIVE | {public} | DELETE | ("userId" = (auth.uid())::text)                                                                                                                                                                                        | 
 public     | User                 | Users can view users in same school                | PERMISSIVE | {public} | SELECT | ("schoolId" = ( SELECT "User_1"."schoolId"                                                                                                                                                                            +| 
            |                      |                                                    |            |          |        |    FROM "User" "User_1"                                                                                                                                                                                               +| 
            |                      |                                                    |            |          |        |   WHERE ("User_1".id = (auth.uid())::text)))                                                                                                                                                                           | 
 public     | User                 | Users can update own profile                       | PERMISSIVE | {public} | UPDATE | (id = (auth.uid())::text)                                                                                                                                                                                              | 
 public     | User                 | Anyone can insert users (signup)                   | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | true
 public     | Athlete              | Athletes can view own profile                      | PERMISSIVE | {public} | SELECT | ("userId" = (auth.uid())::text)                                                                                                                                                                                        | 
 public     | Athlete              | Coaches can view assigned athletes                 | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM "CoachAthleteRelation" car                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |   WHERE ((car."athleteId" = "Athlete"."userId") AND (car."coachId" = (auth.uid())::text) AND (car."consentGranted" = true))))                                                                                          | 
 public     | Athlete              | Athletes can update own profile                    | PERMISSIVE | {public} | UPDATE | ("userId" = (auth.uid())::text)                                                                                                                                                                                        | 
 public     | Athlete              | Athletes can insert own profile                    | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | ("userId" = (auth.uid())::text)
 public     | Coach                | Coaches can view own profile                       | PERMISSIVE | {public} | SELECT | ("userId" = (auth.uid())::text)                                                                                                                                                                                        | 
 public     | TokenUsage           | System can create token usage records              | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | true
 public     | Coach                | Athletes can view their coaches                    | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM "CoachAthleteRelation" car                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |   WHERE ((car."coachId" = "Coach"."userId") AND (car."athleteId" = (auth.uid())::text))))                                                                                                                              | 
 public     | Coach                | Coaches can update own profile                     | PERMISSIVE | {public} | UPDATE | ("userId" = (auth.uid())::text)                                                                                                                                                                                        | 
 public     | Coach                | Coaches can insert own profile                     | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | ("userId" = (auth.uid())::text)
 public     | CoachAthleteRelation | Athletes can view their coach relationships        | PERMISSIVE | {public} | SELECT | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | CoachAthleteRelation | Coaches can view their athlete relationships       | PERMISSIVE | {public} | SELECT | ("coachId" = (auth.uid())::text)                                                                                                                                                                                       | 
 public     | CoachAthleteRelation | Athletes can update consent                        | PERMISSIVE | {public} | UPDATE | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | CoachAthleteRelation | Coaches can create relationships                   | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | ("coachId" = (auth.uid())::text)
 public     | ChatSession          | Athletes can view own chat sessions                | PERMISSIVE | {public} | SELECT | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | ChatSession          | Athletes can create own chat sessions              | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | ("athleteId" = (auth.uid())::text)
 public     | ChatSession          | Athletes can update own chat sessions              | PERMISSIVE | {public} | UPDATE | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | Goal                 | Athletes can view own goals                        | PERMISSIVE | {public} | SELECT | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | Message              | Athletes can view messages in own sessions         | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM "ChatSession" cs                                                                                                                                                                                              +| 
            |                      |                                                    |            |          |        |   WHERE ((cs.id = "Message"."sessionId") AND (cs."athleteId" = (auth.uid())::text))))                                                                                                                                  | 
 public     | Message              | Athletes can create messages in own sessions       | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | (EXISTS ( SELECT 1                                                                                                                     +
            |                      |                                                    |            |          |        |                                                                                                                                                                                                                        |    FROM "ChatSession" cs                                                                                                               +
            |                      |                                                    |            |          |        |                                                                                                                                                                                                                        |   WHERE ((cs.id = "Message"."sessionId") AND (cs."athleteId" = (auth.uid())::text))))
 public     | chat_summaries       | Athletes can view own chat summaries               | PERMISSIVE | {public} | SELECT | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | chat_summaries       | Coaches can view summaries with athlete consent    | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM ("Athlete" a                                                                                                                                                                                                  +| 
            |                      |                                                    |            |          |        |      JOIN "CoachAthleteRelation" car ON ((car."athleteId" = a."userId")))                                                                                                                                             +| 
            |                      |                                                    |            |          |        |   WHERE ((a."userId" = chat_summaries."athleteId") AND (car."coachId" = (auth.uid())::text) AND (a."consentChatSummaries" = true) AND (chat_summaries."revokedAt" IS NULL) AND (chat_summaries."expiresAt" > now())))) | 
 public     | chat_summaries       | System can insert chat summaries                   | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | true
 public     | chat_summaries       | Athletes can update summaries (revoke consent)     | PERMISSIVE | {public} | UPDATE | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | MoodLog              | Athletes can view own mood logs                    | PERMISSIVE | {public} | SELECT | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | MoodLog              | Coaches can view mood logs with consent            | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM "CoachAthleteRelation" car                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |   WHERE ((car."athleteId" = "MoodLog"."athleteId") AND (car."coachId" = (auth.uid())::text) AND (car."consentGranted" = true))))                                                                                       | 
 public     | MoodLog              | Athletes can create own mood logs                  | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | ("athleteId" = (auth.uid())::text)
 public     | MoodLog              | Athletes can delete own mood logs                  | PERMISSIVE | {public} | DELETE | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | Goal                 | Coaches can view athlete goals with consent        | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM "CoachAthleteRelation" car                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |   WHERE ((car."athleteId" = "Goal"."athleteId") AND (car."coachId" = (auth.uid())::text) AND (car."consentGranted" = true))))                                                                                          | 
 public     | Goal                 | Athletes can manage own goals                      | PERMISSIVE | {public} | ALL    | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | ("athleteId" = (auth.uid())::text)
 public     | PerformanceMetric    | Athletes can view own performance metrics          | PERMISSIVE | {public} | SELECT | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | PerformanceMetric    | Coaches can view athlete performance with consent  | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM "CoachAthleteRelation" car                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |   WHERE ((car."athleteId" = "PerformanceMetric"."athleteId") AND (car."coachId" = (auth.uid())::text) AND (car."consentGranted" = true))))                                                                             | 
 public     | PerformanceMetric    | Athletes can manage own performance metrics        | PERMISSIVE | {public} | ALL    | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | ("athleteId" = (auth.uid())::text)
 public     | CrisisAlert          | Athletes can view own crisis alerts                | PERMISSIVE | {public} | SELECT | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | CrisisAlert          | Coaches can view crisis alerts for their athletes  | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM "CoachAthleteRelation" car                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |   WHERE ((car."athleteId" = "CrisisAlert"."athleteId") AND (car."coachId" = (auth.uid())::text))))                                                                                                                     | 
 public     | CrisisAlert          | Coaches can update crisis alerts (review)          | PERMISSIVE | {public} | UPDATE | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM "CoachAthleteRelation" car                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |   WHERE ((car."athleteId" = "CrisisAlert"."athleteId") AND (car."coachId" = (auth.uid())::text))))                                                                                                                     | 
 public     | Assignment           | Coaches can view own assignments                   | PERMISSIVE | {public} | SELECT | ("coachId" = (auth.uid())::text)                                                                                                                                                                                       | 
 public     | Assignment           | Athletes can view assignments targeted to them     | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM "CoachAthleteRelation" car                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |   WHERE ((car."coachId" = "Assignment"."coachId") AND (car."athleteId" = (auth.uid())::text))))                                                                                                                        | 
 public     | Assignment           | Coaches can manage own assignments                 | PERMISSIVE | {public} | ALL    | ("coachId" = (auth.uid())::text)                                                                                                                                                                                       | ("coachId" = (auth.uid())::text)
 public     | AssignmentSubmission | Athletes can view own submissions                  | PERMISSIVE | {public} | SELECT | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | AssignmentSubmission | Coaches can view submissions for their assignments | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM "Assignment" a                                                                                                                                                                                                +| 
            |                      |                                                    |            |          |        |   WHERE ((a.id = "AssignmentSubmission"."assignmentId") AND (a."coachId" = (auth.uid())::text))))                                                                                                                      | 
 public     | AssignmentSubmission | Athletes can manage own submissions                | PERMISSIVE | {public} | ALL    | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | ("athleteId" = (auth.uid())::text)
 public     | CoachNote            | Coaches can view own notes                         | PERMISSIVE | {public} | SELECT | ("coachId" = (auth.uid())::text)                                                                                                                                                                                       | 
 public     | CoachNote            | Coaches can manage own notes                       | PERMISSIVE | {public} | ALL    | ("coachId" = (auth.uid())::text)                                                                                                                                                                                       | ("coachId" = (auth.uid())::text)
 public     | Task                 | Athletes can manage own tasks                      | PERMISSIVE | {public} | ALL    | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | ("athleteId" = (auth.uid())::text)
 public     | Task                 | Coaches can view athlete tasks with consent        | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM "CoachAthleteRelation" car                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |   WHERE ((car."athleteId" = "Task"."athleteId") AND (car."coachId" = (auth.uid())::text) AND (car."consentGranted" = true))))                                                                                          | 
 public     | ReadinessScore       | Athletes can view own readiness scores             | PERMISSIVE | {public} | SELECT | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | ReadinessScore       | Coaches can view athlete readiness with consent    | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM "CoachAthleteRelation" car                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |   WHERE ((car."athleteId" = "ReadinessScore"."athleteId") AND (car."coachId" = (auth.uid())::text) AND (car."consentGranted" = true))))                                                                                | 
 public     | ReadinessScore       | System can create readiness scores                 | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | true
 public     | WearableData         | Athletes can manage own wearable data              | PERMISSIVE | {public} | ALL    | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | ("athleteId" = (auth.uid())::text)
 public     | WearableData         | Coaches can view wearable data with consent        | PERMISSIVE | {public} | SELECT | (EXISTS ( SELECT 1                                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |    FROM "CoachAthleteRelation" car                                                                                                                                                                                    +| 
            |                      |                                                    |            |          |        |   WHERE ((car."athleteId" = "WearableData"."athleteId") AND (car."coachId" = (auth.uid())::text) AND (car."consentGranted" = true))))                                                                                  | 
 public     | TaskPattern          | Athletes can view own task patterns                | PERMISSIVE | {public} | SELECT | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | TaskPattern          | System can create task patterns                    | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | true
 public     | UserSettings         | Users can manage own settings                      | PERMISSIVE | {public} | ALL    | ("userId" = (auth.uid())::text)                                                                                                                                                                                        | ("userId" = (auth.uid())::text)
 public     | PushToken            | Users can manage own push tokens                   | PERMISSIVE | {public} | ALL    | ("userId" = (auth.uid())::text)                                                                                                                                                                                        | ("userId" = (auth.uid())::text)
 public     | AuditLog             | Users can view own audit logs                      | PERMISSIVE | {public} | SELECT | (("userId" = (auth.uid())::text) OR (( SELECT "User".role                                                                                                                                                             +| 
            |                      |                                                    |            |          |        |    FROM "User"                                                                                                                                                                                                        +| 
            |                      |                                                    |            |          |        |   WHERE ("User".id = (auth.uid())::text)) = 'ADMIN'::"Role"))                                                                                                                                                          | 
 public     | AuditLog             | System can create audit logs                       | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | true
 public     | TokenUsage           | Users can view own token usage                     | PERMISSIVE | {public} | SELECT | (("userId" = (auth.uid())::text) OR (( SELECT "User".role                                                                                                                                                             +| 
            |                      |                                                    |            |          |        |    FROM "User"                                                                                                                                                                                                        +| 
            |                      |                                                    |            |          |        |   WHERE ("User".id = (auth.uid())::text)) = 'ADMIN'::"Role"))                                                                                                                                                          | 
 public     | ErrorLog             | Users can view own error logs                      | PERMISSIVE | {public} | SELECT | (("userId" = (auth.uid())::text) OR (( SELECT "User".role                                                                                                                                                             +| 
            |                      |                                                    |            |          |        |    FROM "User"                                                                                                                                                                                                        +| 
            |                      |                                                    |            |          |        |   WHERE ("User".id = (auth.uid())::text)) = 'ADMIN'::"Role"))                                                                                                                                                          | 
 public     | ErrorLog             | System can create error logs                       | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | true
 public     | ConversationInsight  | Athletes can view own conversation insights        | PERMISSIVE | {public} | SELECT | ("athleteId" = (auth.uid())::text)                                                                                                                                                                                     | 
 public     | ConversationInsight  | System can create insights                         | PERMISSIVE | {public} | INSERT |                                                                                                                                                                                                                        | true
 public     | School               | Users can view own school                          | PERMISSIVE | {public} | SELECT | (id = ( SELECT "User"."schoolId"                                                                                                                                                                                      +| 
            |                      |                                                    |            |          |        |    FROM "User"                                                                                                                                                                                                        +| 
            |                      |                                                    |            |          |        |   WHERE ("User".id = (auth.uid())::text)))                                                                                                                                                                             | 
 public     | School               | Admins can manage schools                          | PERMISSIVE | {public} | ALL    | (( SELECT "User".role                                                                                                                                                                                                 +| (( SELECT "User".role                                                                                                                  +
            |                      |                                                    |            |          |        |    FROM "User"                                                                                                                                                                                                        +|    FROM "User"                                                                                                                         +
            |                      |                                                    |            |          |        |   WHERE ("User".id = (auth.uid())::text)) = 'ADMIN'::"Role")                                                                                                                                                           |   WHERE ("User".id = (auth.uid())::text)) = 'ADMIN'::"Role")
 public     | KnowledgeBase        | Users can view knowledge base for their school     | PERMISSIVE | {public} | SELECT | (("schoolId" IS NULL) OR ("schoolId" = ( SELECT "User"."schoolId"                                                                                                                                                     +| 
            |                      |                                                    |            |          |        |    FROM "User"                                                                                                                                                                                                        +| 
            |                      |                                                    |            |          |        |   WHERE ("User".id = (auth.uid())::text))))                                                                                                                                                                            | 
 public     | KnowledgeBase        | Admins can manage knowledge base                   | PERMISSIVE | {public} | ALL    | (( SELECT "User".role                                                                                                                                                                                                 +| (( SELECT "User".role                                                                                                                  +
            |                      |                                                    |            |          |        |    FROM "User"                                                                                                                                                                                                        +|    FROM "User"                                                                                                                         +
            |                      |                                                    |            |          |        |   WHERE ("User".id = (auth.uid())::text)) = 'ADMIN'::"Role")                                                                                                                                                           |   WHERE ("User".id = (auth.uid())::text)) = 'ADMIN'::"Role")
 public     | TeamConfig           | Users can view team config for their school        | PERMISSIVE | {public} | SELECT | ("schoolId" = ( SELECT "User"."schoolId"                                                                                                                                                                              +| 
            |                      |                                                    |            |          |        |    FROM "User"                                                                                                                                                                                                        +| 
            |                      |                                                    |            |          |        |   WHERE ("User".id = (auth.uid())::text)))                                                                                                                                                                             | 
 public     | TeamConfig           | Coaches can manage team config                     | PERMISSIVE | {public} | ALL    | ((( SELECT "User".role                                                                                                                                                                                                +| ((( SELECT "User".role                                                                                                                 +
            |                      |                                                    |            |          |        |    FROM "User"                                                                                                                                                                                                        +|    FROM "User"                                                                                                                         +
            |                      |                                                    |            |          |        |   WHERE ("User".id = (auth.uid())::text)) = ANY (ARRAY['COACH'::"Role", 'ADMIN'::"Role"])) AND ("schoolId" = ( SELECT "User"."schoolId"                                                                               +|   WHERE ("User".id = (auth.uid())::text)) = ANY (ARRAY['COACH'::"Role", 'ADMIN'::"Role"])) AND ("schoolId" = ( SELECT "User"."schoolId"+
            |                      |                                                    |            |          |        |    FROM "User"                                                                                                                                                                                                        +|    FROM "User"                                                                                                                         +
            |                      |                                                    |            |          |        |   WHERE ("User".id = (auth.uid())::text))))                                                                                                                                                                            |   WHERE ("User".id = (auth.uid())::text))))
 public     | VerificationToken    | Anyone can read verification tokens                | PERMISSIVE | {public} | SELECT | true                                                                                                                                                                                                                   | 
 public     | VerificationToken    | System can manage verification tokens              | PERMISSIVE | {public} | ALL    | true                                                                                                                                                                                                                   | true
(79 rows)

