/**
 * ROI Dashboard Screen
 *
 * Executive-friendly metrics for Athletic Directors to justify
 * sports psychology program investment.
 *
 * Features:
 * - Key highlight cards
 * - Engagement metrics
 * - Mental health outcomes
 * - Performance correlation
 * - Efficiency gains
 * - Export capabilities
 */

import { useState, useEffect, useRef } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
  Animated,
  RefreshControl,
  Share,
  Alert,
} from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import * as Haptics from 'expo-haptics';
import { Colors, Spacing, Typography, BorderRadius } from '../../constants/theme';
import { getROIMetrics, ROIMetrics } from '../../lib/services/roi';

export default function ROIDashboardScreen() {
  const router = useRouter();
  const [metrics, setMetrics] = useState<ROIMetrics | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const fadeAnim = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    loadMetrics();
  }, []);

  const loadMetrics = async (isRefresh = false) => {
    if (isRefresh) {
      setRefreshing(true);
    }

    try {
      const data = await getROIMetrics();
      setMetrics(data);

      Animated.timing(fadeAnim, {
        toValue: 1,
        duration: 500,
        useNativeDriver: true,
      }).start();
    } catch (error) {
      console.error('Failed to load ROI metrics:', error);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  const handleExport = async () => {
    if (!metrics) return;

    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);

    const report = `
ROI Dashboard Report
Generated: ${new Date().toLocaleDateString()}
Period: ${metrics.periodComparison.currentPeriod}

KEY HIGHLIGHTS
==============
${metrics.highlights.map((h) => `• ${h.title}: ${h.value} ${h.changeLabel || ''}`).join('\n')}

ENGAGEMENT METRICS
==================
• Total Athletes: ${metrics.engagement.totalAthletes}
• Active Athletes: ${metrics.engagement.activeAthletes} (${metrics.engagement.engagementRate}%)
• Weekly Active Users: ${metrics.engagement.weeklyActiveUsers}
• Total Chat Sessions: ${metrics.engagement.totalChatSessions}
• Total Check-ins: ${metrics.engagement.totalCheckIns}
• Engagement Trend: ${metrics.engagement.engagementTrend} (${metrics.engagement.engagementChange > 0 ? '+' : ''}${metrics.engagement.engagementChange}%)

MENTAL HEALTH OUTCOMES
=====================
• Average Mood Score: ${metrics.mentalHealth.avgMoodScore}/10
• Mood Improvement: ${metrics.mentalHealth.avgMoodChange > 0 ? '+' : ''}${metrics.mentalHealth.avgMoodChange}
• Stress Reduction: ${metrics.mentalHealth.avgStressReduction}
• Confidence Gain: ${metrics.mentalHealth.avgConfidenceGain}
• Athletes Improved: ${metrics.mentalHealth.athletesImproved} (${metrics.mentalHealth.improvementRate}%)

PERFORMANCE CORRELATION
======================
• Win Rate (High Mood): ${metrics.performance.winRateHighMood}%
• Win Rate (Low Mood): ${metrics.performance.winRateLowMood}%
• Performance Gain: +${metrics.performance.performanceGain}%

RISK MITIGATION
==============
• Crisis Alerts Detected: ${metrics.riskMitigation.crisisAlertsDetected}
• Alerts Resolved: ${metrics.riskMitigation.crisisAlertsResolved}
• Early Interventions: ${metrics.riskMitigation.earlyInterventions}

EFFICIENCY
==========
• Estimated Hours Saved: ${metrics.efficiency.estimatedHoursSaved}h
• Average Response Time: ${metrics.efficiency.avgResponseTime}
• Automated Alerts: ${metrics.efficiency.automatedAlerts}

---
Generated by AI Sports Agent
    `.trim();

    try {
      await Share.share({
        message: report,
        title: 'ROI Dashboard Report',
      });
    } catch (error) {
      Alert.alert('Export Error', 'Failed to export report. Please try again.');
    }
  };

  if (loading || !metrics) {
    return (
      <View style={styles.loadingContainer}>
        <LinearGradient
          colors={[Colors.background, Colors.card]}
          style={StyleSheet.absoluteFill}
        />
        <Ionicons name="bar-chart" size={48} color={Colors.primary} />
        <Text style={styles.loadingText}>Loading ROI metrics...</Text>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <LinearGradient
        colors={[Colors.background, Colors.card, Colors.cardElevated]}
        style={StyleSheet.absoluteFill}
      />

      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backButton}>
          <Ionicons name="arrow-back" size={24} color="#fff" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>ROI Dashboard</Text>
        <TouchableOpacity onPress={handleExport} style={styles.exportButton}>
          <Ionicons name="share-outline" size={22} color="#fff" />
        </TouchableOpacity>
      </View>

      <ScrollView
        style={styles.content}
        contentContainerStyle={styles.contentContainer}
        showsVerticalScrollIndicator={false}
        refreshControl={
          <RefreshControl
            refreshing={refreshing}
            onRefresh={() => loadMetrics(true)}
            tintColor="#fff"
          />
        }
      >
        <Animated.View style={{ opacity: fadeAnim }}>
          {/* Period Info */}
          <View style={styles.periodBadge}>
            <Ionicons name="calendar-outline" size={14} color={Colors.textSecondary} />
            <Text style={styles.periodText}>{metrics.periodComparison.currentPeriod}</Text>
          </View>

          {/* Key Highlights */}
          <Text style={styles.sectionTitle}>Key Highlights</Text>
          <View style={styles.highlightsGrid}>
            {metrics.highlights.map((highlight, index) => (
              <HighlightCard key={index} highlight={highlight} />
            ))}
          </View>

          {/* Engagement */}
          <Text style={styles.sectionTitle}>Engagement</Text>
          <View style={styles.metricsCard}>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Total Athletes</Text>
              <Text style={styles.metricValue}>{metrics.engagement.totalAthletes}</Text>
            </View>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Active Athletes</Text>
              <View style={styles.metricValueWithBadge}>
                <Text style={styles.metricValue}>{metrics.engagement.activeAthletes}</Text>
                <View style={styles.percentBadge}>
                  <Text style={styles.percentText}>{metrics.engagement.engagementRate}%</Text>
                </View>
              </View>
            </View>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Weekly Active Users</Text>
              <Text style={styles.metricValue}>{metrics.engagement.weeklyActiveUsers}</Text>
            </View>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Chat Sessions</Text>
              <Text style={styles.metricValue}>{metrics.engagement.totalChatSessions}</Text>
            </View>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Check-ins</Text>
              <Text style={styles.metricValue}>{metrics.engagement.totalCheckIns}</Text>
            </View>
            <View style={[styles.metricRow, styles.metricRowLast]}>
              <Text style={styles.metricLabel}>Trend</Text>
              <View style={styles.trendContainer}>
                <Ionicons
                  name={
                    metrics.engagement.engagementTrend === 'up'
                      ? 'trending-up'
                      : metrics.engagement.engagementTrend === 'down'
                      ? 'trending-down'
                      : 'remove'
                  }
                  size={18}
                  color={
                    metrics.engagement.engagementTrend === 'up'
                      ? '#22c55e'
                      : metrics.engagement.engagementTrend === 'down'
                      ? '#ef4444'
                      : Colors.textSecondary
                  }
                />
                <Text
                  style={[
                    styles.trendText,
                    {
                      color:
                        metrics.engagement.engagementChange >= 0 ? '#22c55e' : '#ef4444',
                    },
                  ]}
                >
                  {metrics.engagement.engagementChange > 0 ? '+' : ''}
                  {metrics.engagement.engagementChange}%
                </Text>
              </View>
            </View>
          </View>

          {/* Mental Health */}
          <Text style={styles.sectionTitle}>Mental Health Outcomes</Text>
          <View style={styles.metricsCard}>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Average Mood</Text>
              <Text style={styles.metricValue}>{metrics.mentalHealth.avgMoodScore}/10</Text>
            </View>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Mood Change</Text>
              <Text
                style={[
                  styles.metricValue,
                  { color: metrics.mentalHealth.avgMoodChange >= 0 ? '#22c55e' : '#ef4444' },
                ]}
              >
                {metrics.mentalHealth.avgMoodChange > 0 ? '+' : ''}
                {metrics.mentalHealth.avgMoodChange}
              </Text>
            </View>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Stress Reduction</Text>
              <Text style={[styles.metricValue, { color: '#22c55e' }]}>
                -{metrics.mentalHealth.avgStressReduction}
              </Text>
            </View>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Confidence Gain</Text>
              <Text style={[styles.metricValue, { color: '#22c55e' }]}>
                +{metrics.mentalHealth.avgConfidenceGain}
              </Text>
            </View>
            <View style={[styles.metricRow, styles.metricRowLast]}>
              <Text style={styles.metricLabel}>Improvement Rate</Text>
              <View style={styles.metricValueWithBadge}>
                <Text style={styles.metricValue}>{metrics.mentalHealth.athletesImproved}</Text>
                <View style={[styles.percentBadge, { backgroundColor: 'rgba(34, 197, 94, 0.2)' }]}>
                  <Text style={[styles.percentText, { color: '#22c55e' }]}>
                    {metrics.mentalHealth.improvementRate}%
                  </Text>
                </View>
              </View>
            </View>
          </View>

          {/* Performance Correlation */}
          <Text style={styles.sectionTitle}>Performance Correlation</Text>
          <View style={styles.performanceCard}>
            <View style={styles.performanceComparison}>
              <View style={styles.performanceItem}>
                <LinearGradient
                  colors={['#22c55e', '#16a34a']}
                  style={styles.performanceIcon}
                >
                  <Ionicons name="happy" size={24} color="#fff" />
                </LinearGradient>
                <Text style={styles.performanceLabel}>High Mood</Text>
                <Text style={styles.performanceValue}>{metrics.performance.winRateHighMood}%</Text>
                <Text style={styles.performanceSubtext}>win rate</Text>
              </View>

              <View style={styles.performanceDivider}>
                <Ionicons name="arrow-forward" size={24} color={Colors.textTertiary} />
                <Text style={styles.performanceGain}>
                  +{metrics.performance.performanceGain}%
                </Text>
              </View>

              <View style={styles.performanceItem}>
                <View style={[styles.performanceIcon, { backgroundColor: Colors.cardElevated }]}>
                  <Ionicons name="sad" size={24} color={Colors.textSecondary} />
                </View>
                <Text style={styles.performanceLabel}>Low Mood</Text>
                <Text style={styles.performanceValue}>{metrics.performance.winRateLowMood}%</Text>
                <Text style={styles.performanceSubtext}>win rate</Text>
              </View>
            </View>
          </View>

          {/* Risk Mitigation */}
          <Text style={styles.sectionTitle}>Risk Mitigation</Text>
          <View style={styles.metricsCard}>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Crisis Alerts Detected</Text>
              <Text style={styles.metricValue}>{metrics.riskMitigation.crisisAlertsDetected}</Text>
            </View>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Alerts Resolved</Text>
              <Text style={[styles.metricValue, { color: '#22c55e' }]}>
                {metrics.riskMitigation.crisisAlertsResolved}
              </Text>
            </View>
            <View style={styles.metricRow}>
              <Text style={styles.metricLabel}>Early Interventions</Text>
              <Text style={styles.metricValue}>{metrics.riskMitigation.earlyInterventions}</Text>
            </View>
            <View style={[styles.metricRow, styles.metricRowLast]}>
              <Text style={styles.metricLabel}>Athletes Recovered</Text>
              <Text style={[styles.metricValue, { color: '#22c55e' }]}>
                {metrics.riskMitigation.athletesRecovered}
              </Text>
            </View>
          </View>

          {/* Efficiency */}
          <Text style={styles.sectionTitle}>Efficiency Gains</Text>
          <View style={styles.efficiencyCard}>
            <View style={styles.efficiencyItem}>
              <LinearGradient
                colors={[Colors.primary, Colors.secondary]}
                style={styles.efficiencyIcon}
              >
                <Ionicons name="time" size={28} color="#fff" />
              </LinearGradient>
              <Text style={styles.efficiencyValue}>{metrics.efficiency.estimatedHoursSaved}h</Text>
              <Text style={styles.efficiencyLabel}>Hours Saved</Text>
            </View>
            <View style={styles.efficiencyItem}>
              <LinearGradient
                colors={['#8b5cf6', '#a855f7']}
                style={styles.efficiencyIcon}
              >
                <Ionicons name="chatbubbles" size={28} color="#fff" />
              </LinearGradient>
              <Text style={styles.efficiencyValue}>
                {metrics.efficiency.chatSessionsReplacing11}
              </Text>
              <Text style={styles.efficiencyLabel}>AI Sessions</Text>
            </View>
            <View style={styles.efficiencyItem}>
              <LinearGradient
                colors={['#f59e0b', '#f97316']}
                style={styles.efficiencyIcon}
              >
                <Ionicons name="notifications" size={28} color="#fff" />
              </LinearGradient>
              <Text style={styles.efficiencyValue}>{metrics.efficiency.automatedAlerts}</Text>
              <Text style={styles.efficiencyLabel}>Auto Alerts</Text>
            </View>
          </View>
        </Animated.View>
      </ScrollView>
    </View>
  );
}

// Highlight Card Component
function HighlightCard({ highlight }: { highlight: ROIMetrics['highlights'][0] }) {
  return (
    <View style={styles.highlightCard}>
      <Text style={styles.highlightTitle}>{highlight.title}</Text>
      <Text style={styles.highlightValue}>{highlight.value}</Text>
      {highlight.change !== undefined && (
        <View style={styles.highlightChange}>
          <Ionicons
            name={highlight.change >= 0 ? 'trending-up' : 'trending-down'}
            size={14}
            color={highlight.positive ? '#22c55e' : '#ef4444'}
          />
          <Text
            style={[styles.highlightChangeText, { color: highlight.positive ? '#22c55e' : '#ef4444' }]}
          >
            {highlight.change > 0 ? '+' : ''}
            {highlight.change}%
          </Text>
        </View>
      )}
      {highlight.changeLabel && (
        <Text style={styles.highlightLabel}>{highlight.changeLabel}</Text>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: Spacing.md,
  },
  loadingText: {
    color: Colors.textSecondary,
    fontSize: Typography.base,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 60,
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.lg,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: Typography.xl,
    fontWeight: '700',
    color: '#fff',
  },
  exportButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: Spacing.lg,
    paddingBottom: 120,
  },
  periodBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: BorderRadius.full,
    alignSelf: 'flex-start',
    marginBottom: Spacing.xl,
  },
  periodText: {
    color: Colors.textSecondary,
    fontSize: Typography.sm,
  },
  sectionTitle: {
    fontSize: Typography.lg,
    fontWeight: '700',
    color: '#fff',
    marginBottom: Spacing.md,
    marginTop: Spacing.lg,
  },
  highlightsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.md,
  },
  highlightCard: {
    width: '47%',
    backgroundColor: Colors.card,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  highlightTitle: {
    fontSize: Typography.sm,
    color: Colors.textSecondary,
    marginBottom: Spacing.xs,
  },
  highlightValue: {
    fontSize: Typography.xxl,
    fontWeight: '800',
    color: '#fff',
  },
  highlightChange: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
    marginTop: Spacing.xs,
  },
  highlightChangeText: {
    fontSize: Typography.sm,
    fontWeight: '600',
  },
  highlightLabel: {
    fontSize: Typography.xs,
    color: Colors.textTertiary,
    marginTop: Spacing.xs,
  },
  metricsCard: {
    backgroundColor: Colors.card,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  metricRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  metricRowLast: {
    borderBottomWidth: 0,
  },
  metricLabel: {
    fontSize: Typography.sm,
    color: Colors.textSecondary,
  },
  metricValue: {
    fontSize: Typography.base,
    fontWeight: '700',
    color: '#fff',
  },
  metricValueWithBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
  },
  percentBadge: {
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    paddingHorizontal: Spacing.sm,
    paddingVertical: 2,
    borderRadius: BorderRadius.full,
  },
  percentText: {
    fontSize: Typography.xs,
    fontWeight: '600',
    color: '#3b82f6',
  },
  trendContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs,
  },
  trendText: {
    fontSize: Typography.sm,
    fontWeight: '600',
  },
  performanceCard: {
    backgroundColor: Colors.card,
    borderRadius: BorderRadius.xl,
    padding: Spacing.xl,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  performanceComparison: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  performanceItem: {
    alignItems: 'center',
    flex: 1,
  },
  performanceIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  performanceLabel: {
    fontSize: Typography.sm,
    color: Colors.textSecondary,
    marginBottom: Spacing.xs,
  },
  performanceValue: {
    fontSize: Typography.xxl,
    fontWeight: '800',
    color: '#fff',
  },
  performanceSubtext: {
    fontSize: Typography.xs,
    color: Colors.textTertiary,
  },
  performanceDivider: {
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
  },
  performanceGain: {
    fontSize: Typography.lg,
    fontWeight: '700',
    color: '#22c55e',
    marginTop: Spacing.xs,
  },
  efficiencyCard: {
    flexDirection: 'row',
    gap: Spacing.md,
  },
  efficiencyItem: {
    flex: 1,
    backgroundColor: Colors.card,
    borderRadius: BorderRadius.xl,
    padding: Spacing.lg,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
  },
  efficiencyIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Spacing.sm,
  },
  efficiencyValue: {
    fontSize: Typography.xl,
    fontWeight: '800',
    color: '#fff',
  },
  efficiencyLabel: {
    fontSize: Typography.xs,
    color: Colors.textSecondary,
    marginTop: Spacing.xs,
    textAlign: 'center',
  },
});
