/**
 * Alerts Panel
 *
 * Displays generated alerts with actions to mark as read or dismiss.
 * Alerts are generated by the rule evaluation system.
 */

'use client';

import { useState, useEffect } from 'react';
import { useSearchParams } from 'next/navigation';
import {
  Bell,
  AlertTriangle,
  AlertCircle,
  Info,
  Check,
  CheckCheck,
  X,
  Clock,
  User,
  RefreshCw,
} from 'lucide-react';
import { DashboardSection } from '../layouts/DashboardGrid';
import {
  generateDemoAlerts,
  type DemoGeneratedAlert,
} from '@/lib/demo-data';

interface GeneratedAlert {
  id: string;
  title: string;
  message: string;
  severity: 'LOW' | 'MEDIUM' | 'HIGH';
  isRead: boolean;
  createdAt: string;
  athleteId: string | null;
  athleteName: string | null;
  metadata: Record<string, unknown> | null;
}

function formatTimeAgo(dateString: string): string {
  const date = new Date(dateString);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMins < 60) return `${diffMins}m ago`;
  if (diffHours < 24) return `${diffHours}h ago`;
  if (diffDays < 7) return `${diffDays}d ago`;
  return date.toLocaleDateString();
}

interface AlertsPanelProps {
  className?: string;
  compact?: boolean;
  maxAlerts?: number;
  onAlertClick?: (alert: GeneratedAlert) => void;
}

export default function AlertsPanel({
  className = '',
  compact = false,
  maxAlerts = 10,
  onAlertClick,
}: AlertsPanelProps) {
  const searchParams = useSearchParams();
  const isDemo = searchParams.get('demo') === 'true';

  const [alerts, setAlerts] = useState<GeneratedAlert[]>([]);
  const [unreadCount, setUnreadCount] = useState(0);
  const [loading, setLoading] = useState(true);
  const [evaluating, setEvaluating] = useState(false);
  const [filter, setFilter] = useState<'all' | 'unread'>('all');

  const fetchAlerts = async () => {
    setLoading(true);

    if (isDemo) {
      const demoData = generateDemoAlerts();
      setAlerts(demoData.alerts as GeneratedAlert[]);
      setUnreadCount(demoData.unreadCount);
      setLoading(false);
      return;
    }

    try {
      const response = await fetch('/api/coach/alerts?limit=' + maxAlerts);
      if (response.ok) {
        const data = await response.json();
        setAlerts(data.alerts);
        setUnreadCount(data.unreadCount);
      }
    } catch (error) {
      console.error('Failed to fetch alerts:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, [isDemo, maxAlerts]);

  const handleMarkAsRead = async (alertId: string, e: React.MouseEvent) => {
    e.stopPropagation();

    if (isDemo) {
      setAlerts(prev => prev.map(a =>
        a.id === alertId ? { ...a, isRead: true } : a
      ));
      setUnreadCount(prev => Math.max(0, prev - 1));
      return;
    }

    try {
      const response = await fetch('/api/coach/alerts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'markRead', alertId }),
      });

      if (response.ok) {
        setAlerts(prev => prev.map(a =>
          a.id === alertId ? { ...a, isRead: true } : a
        ));
        setUnreadCount(prev => Math.max(0, prev - 1));
      }
    } catch (error) {
      console.error('Failed to mark alert as read:', error);
    }
  };

  const handleMarkAllAsRead = async () => {
    if (isDemo) {
      setAlerts(prev => prev.map(a => ({ ...a, isRead: true })));
      setUnreadCount(0);
      return;
    }

    try {
      const response = await fetch('/api/coach/alerts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'markAllRead' }),
      });

      if (response.ok) {
        setAlerts(prev => prev.map(a => ({ ...a, isRead: true })));
        setUnreadCount(0);
      }
    } catch (error) {
      console.error('Failed to mark all as read:', error);
    }
  };

  const handleDismiss = async (alertId: string, e: React.MouseEvent) => {
    e.stopPropagation();

    if (isDemo) {
      const alert = alerts.find(a => a.id === alertId);
      setAlerts(prev => prev.filter(a => a.id !== alertId));
      if (alert && !alert.isRead) {
        setUnreadCount(prev => Math.max(0, prev - 1));
      }
      return;
    }

    try {
      const response = await fetch('/api/coach/alerts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'dismiss', alertId }),
      });

      if (response.ok) {
        const alert = alerts.find(a => a.id === alertId);
        setAlerts(prev => prev.filter(a => a.id !== alertId));
        if (alert && !alert.isRead) {
          setUnreadCount(prev => Math.max(0, prev - 1));
        }
      }
    } catch (error) {
      console.error('Failed to dismiss alert:', error);
    }
  };

  const handleEvaluateRules = async () => {
    setEvaluating(true);

    if (isDemo) {
      // Simulate evaluation delay
      await new Promise(resolve => setTimeout(resolve, 1000));
      setEvaluating(false);
      return;
    }

    try {
      await fetch('/api/coach/alerts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'evaluate' }),
      });
      // Refresh alerts after evaluation
      await fetchAlerts();
    } catch (error) {
      console.error('Failed to evaluate rules:', error);
    } finally {
      setEvaluating(false);
    }
  };

  const getSeverityStyles = (severity: string) => {
    switch (severity) {
      case 'HIGH':
        return {
          bg: 'bg-red-500/10',
          border: 'border-red-500/30',
          icon: <AlertTriangle className="w-4 h-4 text-red-400" />,
          badge: 'bg-red-500/20 text-red-400',
        };
      case 'MEDIUM':
        return {
          bg: 'bg-amber-500/10',
          border: 'border-amber-500/30',
          icon: <AlertCircle className="w-4 h-4 text-amber-400" />,
          badge: 'bg-amber-500/20 text-amber-400',
        };
      default:
        return {
          bg: 'bg-blue-500/10',
          border: 'border-blue-500/30',
          icon: <Info className="w-4 h-4 text-blue-400" />,
          badge: 'bg-blue-500/20 text-blue-400',
        };
    }
  };

  const filteredAlerts = filter === 'unread'
    ? alerts.filter(a => !a.isRead)
    : alerts;

  if (loading) {
    return (
      <DashboardSection title="Alerts">
        <div className="space-y-3">
          {[1, 2, 3].map(i => (
            <div key={i} className="h-16 bg-slate-800 rounded-lg animate-pulse" />
          ))}
        </div>
      </DashboardSection>
    );
  }

  return (
    <div className={className}>
      <DashboardSection
        title={
          <div className="flex items-center gap-2">
            <span>Alerts</span>
            {unreadCount > 0 && (
              <span className="px-2 py-0.5 text-xs font-semibold bg-red-500 text-white rounded-full">
                {unreadCount}
              </span>
            )}
          </div>
        }
        action={
          <div className="flex items-center gap-2">
            {!compact && (
              <>
                <button
                  onClick={handleEvaluateRules}
                  disabled={evaluating}
                  className="flex items-center gap-1.5 px-2 py-1 text-xs text-slate-400 hover:text-white hover:bg-slate-700 rounded"
                  title="Re-evaluate all rules now"
                >
                  <RefreshCw className={`w-3.5 h-3.5 ${evaluating ? 'animate-spin' : ''}`} />
                  {evaluating ? 'Checking...' : 'Check Now'}
                </button>
                {unreadCount > 0 && (
                  <button
                    onClick={handleMarkAllAsRead}
                    className="flex items-center gap-1.5 px-2 py-1 text-xs text-slate-400 hover:text-white hover:bg-slate-700 rounded"
                  >
                    <CheckCheck className="w-3.5 h-3.5" />
                    Mark All Read
                  </button>
                )}
              </>
            )}
          </div>
        }
      >
        {!compact && alerts.length > 0 && (
          <div className="flex gap-2 mb-4">
            <button
              onClick={() => setFilter('all')}
              className={`px-3 py-1 text-sm rounded-full ${
                filter === 'all'
                  ? 'bg-slate-700 text-white'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              All ({alerts.length})
            </button>
            <button
              onClick={() => setFilter('unread')}
              className={`px-3 py-1 text-sm rounded-full ${
                filter === 'unread'
                  ? 'bg-slate-700 text-white'
                  : 'text-slate-400 hover:text-white'
              }`}
            >
              Unread ({unreadCount})
            </button>
          </div>
        )}

        {filteredAlerts.length === 0 ? (
          <div className="text-center py-8">
            <Bell className="w-12 h-12 text-slate-600 mx-auto mb-3" />
            <p className="text-slate-400">
              {filter === 'unread' ? 'No unread alerts' : 'No alerts to show'}
            </p>
            <p className="text-xs text-slate-500 mt-1">
              Alerts are generated when your rules are triggered
            </p>
          </div>
        ) : (
          <div className="space-y-2">
            {filteredAlerts.slice(0, maxAlerts).map(alert => {
              const styles = getSeverityStyles(alert.severity);
              return (
                <div
                  key={alert.id}
                  onClick={() => onAlertClick?.(alert)}
                  className={`p-3 rounded-lg border ${styles.bg} ${styles.border} ${
                    !alert.isRead ? 'ring-1 ring-inset ring-white/10' : ''
                  } ${onAlertClick ? 'cursor-pointer hover:brightness-110' : ''} transition-all`}
                >
                  <div className="flex items-start gap-3">
                    <div className="mt-0.5">{styles.icon}</div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-0.5">
                        <h4 className={`text-sm font-medium ${
                          alert.isRead ? 'text-slate-400' : 'text-white'
                        }`}>
                          {alert.title}
                        </h4>
                        {!alert.isRead && (
                          <span className="w-2 h-2 rounded-full bg-blue-500" />
                        )}
                      </div>
                      <p className={`text-xs ${
                        alert.isRead ? 'text-slate-500' : 'text-slate-300'
                      }`}>
                        {alert.message}
                      </p>
                      <div className="flex items-center gap-3 mt-2">
                        {alert.athleteName && (
                          <span className="flex items-center gap-1 text-xs text-slate-500">
                            <User className="w-3 h-3" />
                            {alert.athleteName}
                          </span>
                        )}
                        <span className="flex items-center gap-1 text-xs text-slate-500">
                          <Clock className="w-3 h-3" />
                          {formatTimeAgo(alert.createdAt)}
                        </span>
                        <span className={`px-1.5 py-0.5 text-xs rounded ${styles.badge}`}>
                          {alert.severity}
                        </span>
                      </div>
                    </div>

                    <div className="flex items-center gap-1">
                      {!alert.isRead && (
                        <button
                          onClick={(e) => handleMarkAsRead(alert.id, e)}
                          className="p-1 hover:bg-slate-700 rounded"
                          title="Mark as read"
                        >
                          <Check className="w-4 h-4 text-slate-400" />
                        </button>
                      )}
                      <button
                        onClick={(e) => handleDismiss(alert.id, e)}
                        className="p-1 hover:bg-slate-700 rounded"
                        title="Dismiss"
                      >
                        <X className="w-4 h-4 text-slate-400 hover:text-red-400" />
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </DashboardSection>
    </div>
  );
}
